version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_event_locator
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_locator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./api
    container_name: event-locator-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event_locator_db
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin
        SPRING_JPA_HIBERNATE_DDL_AUTO: validate
        SPRING_JPA_SHOW_SQL: true
        SPRING_FLYWAY_ENABLED: true
        SPRING_FLYWAY_LOCATIONS: classpath:db/migration
        SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
    ports:
      - "8083:8083"
    restart: always

  frontend:
    build: ./frontend
    container_name: event-locator-ui
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:4200"
    restart: always

  nginx:
    image: nginx:latest
    container_name: event-locator-nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
    postgres_data:
        driver: local